services:
    web:
        image: php:8.2-apache
        container_name: php
        ports:
            - "8075:80"
        volumes:
            - ./app:/var/www/html
        networks:
            - app-network
        build:
            context: .
            dockerfile: Dockerfile

networks:
    app-network:
        driver: bridge